#!/usr/bin/env ruby
# vim: set ft=ruby:

STDOUT.sync = STDERR.sync = true

begin
  require 'rubygems'
  require 'bundler'
  require 'bundler/setup'
rescue => e
  STDERR.puts e.message
end

require_relative './gorack_server'


Gorack::Server.run(ARGV[0])
