#!/usr/bin/env ruby
# vim: set ft=ruby:

STDOUT.sync = STDERR.sync = true

require 'rack'
require 'socket'
require_relative '../lib/gorack.rb'

app, app_options = Rack::Builder.parse_file(ARGV[0])

Gorack::Server.run(
  UNIXSocket.for_fd(3), # IO descriptor inherited from parent process
  app,
  app_options
)
