#!/usr/bin/env ruby
# vim: set ft=ruby:

STDOUT.sync = STDERR.sync = true

require 'rack'
require 'socket'
require_relative '../lib/gorack.rb'

# descriptor inherited from parent process
master_sock = UNIXSocket.for_fd(3)

Gorack::Server.run(master_sock, ARGV[0])
