#!/usr/bin/env ruby
# vim: set ft=ruby:

STDOUT.sync = STDERR.sync = true

require 'rack'
require 'socket'
require 'logger'
require_relative '../lib/gorack.rb'

logger = Logger.new(STDOUT)
logger.formatter = proc do |severity, datetime, progname, msg|
  "[PID:#{Process.pid}] #{msg}\n"
end

app, app_options = Rack::Builder.parse_file(ARGV[0])
server = Gorack::Server.new(
  UNIXSocket.for_fd(3), # IO descriptor inherited from parent process
  app,
  app_options,
  logger
)

at_exit { server.exit }

server.run
